#! /bin/sh

cat << HEAD > index.md
---
title: Brendon O'Laney
---

::: {.header}

# Brendon O'Laney

## Index

:::

HEAD

#shellcheck disable=SC2035,SC2045
for entry in $(ls -r *.md)
do
	if [ "${entry}" = "index.md" ]
	then
		continue
	fi
	title=$(grep -i 'title:' "$entry" | head -1 | sed 's/title: \(.*\)/\1/')
	date="${entry%\.md}"
	echo "- [${title}](./${entry%\.md}.html) (${date})" >> index.md
done

cat << END >> index.md

::: {.footer}

[Back](../index.html)
[RSS](./rss.xml)

:::
END
