#! /bin/sh

build_date=$(date -R)

cat <<- HEAD > rss.xml
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
<atom:link
	href="https://brendonolaney.com/blog/rss.xml"
	rel="self"
	type="application/rss+xml"
/>
<title>Brendon O'Laney</title>
<description>Index</description>
<link>https://brendonolaney.com/blog</link>
<lastBuildDate>${build_date}</lastBuildDate>
<managingEditor>
	brendon@brendonolaney.com Brendon O'Laney
</managingEditor>
HEAD

#shellcheck disable=SC2035,SC2045
for entry in $(ls -r *.md)
do
	if [ "${entry}" = "index.md" ]
	then
		continue
	fi

	system=$(uname)

	title=$(grep -i 'title:' "$entry" | \
		head -1 | \
		sed 's/title: \(.*\)/\1/')
	in_date=$(grep -i 'date:' "$entry" | \
		head -1 | \
		sed 's/date: \(.*\)/\1/')

	if [ "${system}" = "Darwin" ]
	then
		out_date=$(echo \
			"${in_date}" | \
			xargs -J \# date -j -f "%Y-%m-%d" \# -R)
	else
		out_date=$(echo \
			"${in_date}" | \
			xargs -I \# date --date="#" -R)
	fi

	description=$(pandoc -t html "${entry}")

	cat <<- ITEM >> rss.xml
	<item>
		<guid>
			https://brendonolaney.com/blog/${entry%\.md}.html
		</guid>
		<link>
			https://brendonolaney.com/blog/${entry%\.md}.html
		</link>
		<pubdate>${out_date}</pubdate>
		<title>${title}</title>
		<description><![CDATA[
			$description
		]]></description>
	</item>
	ITEM
done

cat << END >> rss.xml
</channel>
</rss>
END
