tgt_dir:=../../www/work
static := $(tgt_dir)/ae.html $(tgt_dir)/fd.html $(tgt_dir)/index.html $(tgt_dir)/ipr.html $(tgt_dir)/loc.html $(tgt_dir)/pp.html $(tgt_dir)/resume.html $(tgt_dir)/snetl.html

all: $(static)

clean:
	rm -f $(tgt_dir)/*

$(tgt_dir)/favicon.ico: favicon.ico
	cp favicon.ico $(tgt_dir)/favicon.ico

$(tgt_dir)/ae.html: ae.html
	cp ae.html $(tgt_dir)/ae.html

$(tgt_dir)/fd.html: fd.html
	cp fd.html $(tgt_dir)/fd.html

$(tgt_dir)/index.html: index.html
	cp index.html $(tgt_dir)/index.html

$(tgt_dir)/ipr.html: ipr.html
	cp ipr.html $(tgt_dir)/ipr.html

$(tgt_dir)/loc.html: loc.html
	cp loc.html $(tgt_dir)/loc.html

$(tgt_dir)/pp.html: pp.html
	cp pp.html $(tgt_dir)/pp.html

$(tgt_dir)/resume.html: resume.html
	cp resume.html $(tgt_dir)/resume.html

$(tgt_dir)/snetl.html: snetl.html
	cp snetl.html $(tgt_dir)/snetl.html

