@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

System(win95, "Windows 95", "")
System_Boundary(bridge, "Email Bridge") {
  System(postfix, "postfix")
  System(maildir, "maildir")
  System(isync, "isync")
  System(dovecot, "dovecot")
}
System_Ext(icloud, "iCloud")

Rel_U(icloud, isync, "Secure IMAP")
Rel_U(postfix, icloud, "Secure SMTP")

Rel(dovecot, win95, "Insecure POP3")
Rel(win95, postfix, "Insecure SMTP")
Rel(maildir, dovecot, "Reads Email")
Rel(isync, maildir, "Writes Email")
@enduml
