tgt_dir:=../../www/img
static := $(tgt_dir)/ae.png $(tgt_dir)/brendon-big.jpg $(tgt_dir)/brendon.jpg $(tgt_dir)/fd.png $(tgt_dir)/loc.png $(tgt_dir)/snetl.png

all: $(static)

clean:
	rm -f $(tgt_dir)/*

$(tgt_dir)/ae.png: ae.png
	cp ae.png $(tgt_dir)/ae.png

$(tgt_dir)/brendon-big.jpg: brendon-big.jpg
	cp brendon-big.jpg $(tgt_dir)/brendon-big.jpg

$(tgt_dir)/brendon.jpg: brendon.jpg
	cp brendon.jpg $(tgt_dir)/brendon.jpg

$(tgt_dir)/fd.png: fd.png
	cp fd.png $(tgt_dir)/fd.png

$(tgt_dir)/loc.png: loc.png
	cp loc.png $(tgt_dir)/loc.png

$(tgt_dir)/snetl.png: snetl.png
	cp snetl.png $(tgt_dir)/snetl.png
